// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5VOl5K8UdF0e48WM19G2lfaxLqXkuZGk',
    appId: '1:180699725989:web:a64bd829a7e9cb1b840d4c',
    messagingSenderId: '180699725989',
    projectId: 'pi5-ms-notificacoes',
    authDomain: 'pi5-ms-notificacoes.firebaseapp.com',
    storageBucket: 'pi5-ms-notificacoes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-30jPJ2FTj27j7_Ai3PmoR-iIoCO9eWQ',
    appId: '1:180699725989:android:2d5830911ed85699840d4c',
    messagingSenderId: '180699725989',
    projectId: 'pi5-ms-notificacoes',
    storageBucket: 'pi5-ms-notificacoes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF00DJi7wBe737aCQxsmymRfzHGCFKVN8',
    appId: '1:180699725989:ios:0d56c90acc18ae44840d4c',
    messagingSenderId: '180699725989',
    projectId: 'pi5-ms-notificacoes',
    storageBucket: 'pi5-ms-notificacoes.firebasestorage.app',
    iosBundleId: 'com.example.pi5MsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF00DJi7wBe737aCQxsmymRfzHGCFKVN8',
    appId: '1:180699725989:ios:0d56c90acc18ae44840d4c',
    messagingSenderId: '180699725989',
    projectId: 'pi5-ms-notificacoes',
    storageBucket: 'pi5-ms-notificacoes.firebasestorage.app',
    iosBundleId: 'com.example.pi5MsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5VOl5K8UdF0e48WM19G2lfaxLqXkuZGk',
    appId: '1:180699725989:web:fb7fda9f40b55e09840d4c',
    messagingSenderId: '180699725989',
    projectId: 'pi5-ms-notificacoes',
    authDomain: 'pi5-ms-notificacoes.firebaseapp.com',
    storageBucket: 'pi5-ms-notificacoes.firebasestorage.app',
  );
}
